let
    Source = Excel.Workbook(File.Contents("D:\งาน\Datacamp\Learn\Power BI\1.Introduction to Power BI\Datasets\Contoso DW\DimEntity(Fixed).csv.xlsx"), null, true),
    EntityCountry_Sheet = Source{[Item="EntityCountry",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(EntityCountry_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EntityCountry", Int64.Type}, {"EntityName", type text}, {"EntityType", type text}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "EntityName", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"EntityName.1", "EntityName.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"EntityName.1", type text}, {"EntityName.2", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"EntityName.1"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"EntityName.2", "EntityCountryName"}})
in
    #"Renamed Columns"